name: Mod Support Request
description: Request support for a specific mod
title: "[Mod Support Request] EXAMPLE MOD"
labels: ["🧩 mod-support"]
body:
  - type: markdown
    attributes:
      value: |
        Before submitting this mod support request, please make sure that your mod has not already been requested in another issue.
        
        If you have multiple mods that you would like to request support for, please submit a **separate issue** for each mod.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Add any context or screenshots about the requested mod below.
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Link to the mod page
      description: Please provide a URL to the mod page.
      placeholder: "Example: https://modrinth.com/resourcepack/default-dark-mode"
    validations:
      required: true

  - type: dropdown
    id: versions
    attributes:
      label: Game versions
      description: What game versions should be supported? Select all applicable game versions. Only the latest 3 major versions are supported.
      multiple: true
      options:
        - "1.21"
        - "1.20"
        - "1.19"
    validations:
      required: true

  - type: dropdown
    id: modloaders
    attributes:
      label: Mod Loaders
      description: What mod loader is the mod using? Select all applicable modloaders.
      multiple: true
      options:
        - Fabric
        - Forge
        - NeoForge
        - Quilt
        - Data Pack
        - Other
    validations:
      required: true